import { Colors } from './constants';

export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column' as const,
    height: '100vh',
    backgroundColor: Colors.safetyYellow,
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  header: {
    backgroundColor: Colors.safetyBlack,
    color: Colors.safetyWhite,
    padding: '16px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: '20px',
    fontWeight: '800',
    flex: 1,
    textAlign: 'center' as const,
  },
  backBtn: {
    backgroundColor: 'transparent',
    border: 'none',
    color: Colors.safetyWhite,
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
    padding: '8px 12px',
    borderRadius: '8px',
    transition: 'background-color 0.2s',
  },
  button: {
    backgroundColor: Colors.safetyRed,
    color: Colors.safetyWhite,
    border: 'none',
    borderRadius: '12px',
    padding: '16px',
    fontSize: '16px',
    fontWeight: '800',
    cursor: 'pointer',
    transition: 'opacity 0.2s',
  },
  buttonSecondary: {
    backgroundColor: Colors.safetyBlack,
    color: Colors.safetyWhite,
    border: 'none',
    borderRadius: '12px',
    padding: '12px 16px',
    fontSize: '14px',
    fontWeight: '700',
    cursor: 'pointer',
    transition: 'opacity 0.2s',
  },
  modal: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: Colors.safetyOverlay,
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: Colors.safetyWhite,
    borderTopLeftRadius: '24px',
    borderTopRightRadius: '24px',
    maxHeight: '90vh',
    width: '100%',
    maxWidth: '600px',
    overflow: 'auto',
  },
};
